"""
Reflector v1.2 — Timothy's AI Agent Swarm
Runs daily at 6:30am AEST (7:30pm UTC) via Railway cron.

Responsibilities:
1. Check + set run lock in system_config (prevents double-run)
2. Read swarm_events, swarm_tasks, swarm_reflections, swarm_sessions from Supabase
3. Rebuild MEMORY.md (200-line cap, last 7 days activity + recent sessions)
4. Rebuild per-agent memory scopes (.claude/agent-memory/<name>/MEMORY.md)
5. Write all files to the timschuster-deploy repo via GitHub API
6. Release run lock
7. Telegram notification (success or failure)
"""

import os
import json
import traceback
from datetime import datetime, timedelta, timezone
from supabase import create_client

# ── Config ─────────────────────────────────────────────────────────────────────
SUPABASE_URL       = os.environ["SUPABASE_URL"]        # swarm-data project
SUPABASE_KEY       = os.environ["SUPABASE_KEY"]
TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHAT_ID   = os.environ["TELEGRAM_CHAT_ID"]
GITHUB_TOKEN       = os.environ["GITHUB_TOKEN"]
GITHUB_REPO        = "timschuster2/timschuster-deploy"  # update if different

import requests

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# ── Telegram ───────────────────────────────────────────────────────────────────
def telegram(msg: str, urgent: bool = False):
    prefix = "🔴" if urgent else "⚪"
    requests.post(
        f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
        json={"chat_id": TELEGRAM_CHAT_ID, "text": f"{prefix} REFLECTOR: {msg}", "parse_mode": "Markdown"},
        timeout=10,
    )

# ── Run lock ───────────────────────────────────────────────────────────────────
def acquire_lock() -> bool:
    """Returns True if lock acquired, False if already running."""
    result = supabase.table("system_config").select("value").eq("key", "reflector_running").execute()
    if result.data and result.data[0]["value"] is True:
        return False
    supabase.table("system_config").upsert(
        {"key": "reflector_running", "value": True, "updated_at": datetime.now(timezone.utc).isoformat()}
    ).execute()
    return True

def release_lock():
    supabase.table("system_config").upsert(
        {"key": "reflector_running", "value": False, "updated_at": datetime.now(timezone.utc).isoformat()}
    ).execute()

# ── Data fetch ─────────────────────────────────────────────────────────────────
def fetch_recent_events(days: int = 7) -> list:
    since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    result = supabase.table("swarm_events").select("*").gte("created_at", since).order("created_at", desc=True).limit(50).execute()
    return result.data or []

def fetch_open_tasks() -> list:
    result = supabase.table("swarm_tasks").select("*").in_("status", ["open", "in_progress"]).order("created_at", desc=True).execute()
    return result.data or []

def fetch_recent_reflections(days: int = 14) -> list:
    since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    result = supabase.table("swarm_reflections").select("*").gte("created_at", since).order("created_at", desc=True).limit(10).execute()
    return result.data or []

def fetch_recent_sessions(days: int = 7) -> list:
    since = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
    result = supabase.table("swarm_sessions").select("*").gte("session_date", since).order("session_date", desc=True).limit(5).execute()
    return result.data or []

# ── Build MEMORY.md (200-line cap) ─────────────────────────────────────────────
def build_memory_md(events: list, tasks: list, reflections: list, sessions: list = None) -> str:
    now = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")
    lines = [
        "# MEMORY.md — Timothy's AI Agent Swarm",
        f"# Generated by Reflector at {now}. Never hand-edit.",
        "",
        "## Identity",
        "- Timothy Schuster (Schuey) | Lead BA Westpac + AI swarm builder",
        "- Claude Max $100/mo | Sydney AEST (UTC+11)",
        "",
        "## Agents",
        "Holly (CSO) | Bob (Builder) | Q (Researcher) | Nobody (Critic) | Astro (Explorer)",
        "",
        "## Recent Events (last 7 days)",
    ]

    for e in events[:15]:
        agent = e.get("agent", "system")
        summary = e.get("summary", e.get("event_type", "event"))
        ts = e.get("created_at", "")[:10]
        lines.append(f"- [{ts}] {agent}: {summary}")

    lines += ["", "## Recent Sessions"]
    if sessions:
        for s in sessions[:5]:
            date = s.get("session_date", "")
            summary = s.get("summary", "")[:100]
            lines.append(f"- [{date}] {summary}")
    else:
        lines.append("- No recent sessions")

    lines += ["", "## Open Tasks"]
    for t in tasks[:10]:
        title = t.get("title", "untitled")
        status = t.get("status", "open")
        priority = t.get("priority", "")
        lines.append(f"- [{status.upper()}] {title}" + (f" ({priority})" if priority else ""))

    if not tasks:
        lines.append("- No open tasks")

    lines += ["", "## Recent Reflections"]
    for r in reflections[:5]:
        content = r.get("content", "")[:120]
        ts = r.get("created_at", "")[:10]
        lines.append(f"- [{ts}] {content}")

    if not reflections:
        lines.append("- None yet")

    lines += [
        "",
        "## Active Infrastructure",
        "- timschuster.dev → Vercel (timschuster-deploy)",
        "- Ideation scanner → Railway cron 8am AEST",
        "- Swarm Telegram bot → Railway",
        "- Supabase swarm-data (isolated from trading-data)",
        "- Trading swarm v4.0 → trading-swarm repo",
        "",
        "## Key Rules",
        "- STP: Projects → outputs file → local save → Claude Code deploys",
        "- Never cross-write swarm-data ↔ trading-data",
        "- Nobody review mandatory before every git push",
    ]

    # Cap at 200 lines
    return "\n".join(lines[:200])

# ── Build per-agent MEMORY.md (50-line cap) ────────────────────────────────────
def build_agent_memory_md(agent_name: str, events: list, tasks: list) -> str:
    now = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")
    agent_events = [e for e in events if e.get("agent", "").lower() == agent_name.lower()]
    agent_tasks = [t for t in tasks if t.get("assigned_to", "").lower() == agent_name.lower()]

    lines = [
        f"# {agent_name.upper()} — Agent Memory",
        f"# Generated by Reflector v1.2 at {now}. Never hand-edit.",
        "",
        "## My Recent Activity",
    ]

    if agent_events:
        for e in agent_events[:10]:
            summary = e.get("summary", e.get("event_type", "event"))
            ts = e.get("created_at", "")[:10]
            lines.append(f"- [{ts}] {summary}")
    else:
        lines.append("- No recent activity")

    lines += ["", "## My Open Tasks"]
    if agent_tasks:
        for t in agent_tasks[:8]:
            title = t.get("title", "untitled")
            status = t.get("status", "open")
            lines.append(f"- [{status.upper()}] {title}")
    else:
        lines.append("- No assigned tasks")

    return "\n".join(lines[:50])

# ── GitHub file write ──────────────────────────────────────────────────────────
def write_to_github(path: str, content: str, message: str):
    """Create or update a file in the GitHub repo via API."""
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    url = f"https://api.github.com/repos/{GITHUB_REPO}/contents/{path}"

    # Get current SHA if file exists
    existing = requests.get(url, headers=headers, timeout=10)
    sha = existing.json().get("sha") if existing.status_code == 200 else None

    import base64
    payload = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch": "main",
    }
    if sha:
        payload["sha"] = sha

    resp = requests.put(url, headers=headers, json=payload, timeout=15)
    resp.raise_for_status()

# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    print(f"Reflector starting — {datetime.now(timezone.utc).isoformat()}")

    if not acquire_lock():
        print("Lock already held — skipping run")
        telegram("⚠️ Skipped — already running", urgent=False)
        return

    try:
        events      = fetch_recent_events(7)
        tasks       = fetch_open_tasks()
        reflections = fetch_recent_reflections(14)
        sessions    = fetch_recent_sessions(7)

        memory_md = build_memory_md(events, tasks, reflections, sessions)

        # Write MEMORY.md to repo
        write_to_github(
            ".swarm/MEMORY.md",
            memory_md,
            "chore(reflector): rebuild MEMORY.md",
        )

        # Write per-agent memory scopes
        agents = ["holly", "q", "nobody", "astro", "bob"]
        agent_count = 0
        for agent in agents:
            agent_md = build_agent_memory_md(agent, events, tasks)
            write_to_github(
                f".claude/agent-memory/{agent}/MEMORY.md",
                agent_md,
                f"chore(reflector): rebuild {agent} agent memory",
            )
            agent_count += 1

        summary = f"✅ Reflector ran. Events: {len(events)}, Tasks: {len(tasks)}, Agent files: {agent_count}"
        print(summary)
        telegram(summary)

    except Exception as e:
        tb = traceback.format_exc()
        print(f"ERROR: {e}\n{tb}")
        telegram(f"🔴 FAILED: {str(e)[:200]}", urgent=True)

    finally:
        release_lock()

if __name__ == "__main__":
    main()
